---
title: "Statistika 1"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## O kurzu 

Tento kurz je koncipován jako první krok do statistiky pro studenty a studentky sociologie. Kurz sleduje dva hlavní cíle. Prvním je u studujících vybudovat/posílit základy datové či statistické gramotnosti, aby mohli být kritickými uživateli statistických výstupů v médiích a postupně také ve vědeckých pracích. Druhým cílem je začít je seznamovat s procesem statistického vyšetřování a s vybranými statistickými postupy, které vědec či analytik v rámci své práce využívá.  Tím by měli studující vykročit na cestu k tomu, aby se sami stali zběhlými tvůrci kvantitativního sociologického poznání. Výuka probíhá formou 90minutové přednášky a 90 minuotvého semináře jednou týdně. Kurz je koncipován jako jednosemestrální a navazuje na něj kurz Statistika 2. Formálně je kurz rozdělen do dvou částí: [Zde najdete přednášku v SIS](https://is.cuni.cz/studium/predmety/index.php?id=c092f48d0faf8dab134342edd4e7ae4a&tid=&do=predmet&kod=ASG100117) a [tady je zase seminář](https://is.cuni.cz/studium/predmety/index.php?id=c092f48d0faf8dab134342edd4e7ae4a&tid=&do=predmet&kod=ASG100118).  

## O webu

Tento web je hlavní elektronickou oporou kurzu. Moodle je v tom kurzu využíván pouze pro složení závěrečného testu a odevzdávání zápočtových a bonusových úkolů. Na tomto webu najdete sylabus s cíli výuky a výsledky učení pro jednotlivé přednášky. Velmi doporučuji s nimi pracovat. Dále zde najdete všechny prezentace k přednáškám, úlohy k procvičování (slouží jako kontrola pro studující, že všemu dobře porozuměli a dokážou to aplikovat), bonusové úkoly (slouží jako příležitost získat průběžnou prací bonusové body pro zlepšení výsledné známky) a datové soubory pro seminář i všechny zadané úkoly. Vlastní karty jsou věnovány podmínkám atestace (včetně zadání zápočtových úkolů) a základní doporučené kurzové literatuře.

## Základní pojmy kurzové administrativy

- **Zápočtové úlohy** - V rámci kurzu je třeba splnit dvě rozsáhlejší povinné zápočtové úlohy. Zadání a podmínky najdete v sekci Atestace.
- **Bonusové úkoly** - Během semestru lze dobrovolně plnit pět bonusových úkolů a získat tak body navíc pro závěrečnou zkoušku. Zadání a podmínky najdete v sekci Bonusové úkoly.
- **Procvičování** - Navíc je v sekci Procvičování pro každé z probíraných témat několik procvičovacích úloh, kde si můžete sami ověřit, jestli zvládáte probranou látku.

## Vyučující

Jmenuji se **Jaromír Mazák**, pracuji na katedře sociologie FF UK jako odborný asistent. Kurz Statistika 1 vyučuji od letního semestru 2022. Výzkumně se věnuji především tématu občanské společnosti a politické participace, ve výuce pak hlavně tématům kvantitativní analýzy dat ([Úvod do analýzy dat v R](https://sociology-fa-cu.github.io/Uvod_do_analyzy_dat_v_R/), [Applied regression in R](https://sociology-fa-cu.github.io/appliedregressioninr/index.html), [Vybraná témata analýzy dat](https://sociology-fa-cu.github.io/vybranatemataanalyzy/index.html)). Více na [profilu na stránkách katedry](https://ksoc.ff.cuni.cz/mazak/). Případně mě kontaktujte [emailem](mailto:jaromir.mazak@ff.cuni.cz), obzvlášť pokud na webu najdete chybu nebo budete mít nějaký podnět - budu vděčný!

Na realizaci kurzu se podílí také pomvědky **Františka Tranová** a **Hana Šiková**.  

Vznik kurzu v roli konzultanta, skeptika i inspirátora významně podpořil **Aleš Vomáčka**.
