---
title: "Prezentace"
output: html_document
---

```{r setup, include=FALSE}
library(fontawesome)
knitr::opts_chunk$set(echo = FALSE)

col_icon <- "#00f"
```

U názvů jednotlivých témat najdete kompletní prezentace k přednáškám. Prezentace nejsou primárně navržené jako materiál pro samostudium, ale jako doprovodný materiál k výkladu. K dispozici jsou dvě verze: HTML verze zobrazitelná přímo v prohlížeči a PDF verze ke stažení. PDF verze neobsahuje poznámky.

Při práci s HTML verzí prezentací je možné využívat následujících klávesových zkratek:

- šipkami je možné přecházet z jednoho snímku na druhý.
- Klávesa `f` spustí zobrazení plné obrazovky (fullscreen)
- Klávesa `w` spustí širokoúhlé zobrazení (widescreen)
- Klávesa `o` zobrazí přehled snímků.
- Klávesa `p` zobrazí poznámku k aktuálnímu snímku (pokud existuje) - doplnění poznámkami má za cíl alespoň částečně usnadnit samostudium těm, kdo se nemohou účastnit přednášek.

Některé prezentace na konci obsahují sekci "Nadstavba". Ta představuje dobrovolné rozšíření probírané látky, nicméně toto rozšíření není předmětem zkoušení ani žádných zadaných úkolů. Na přednášce se zpravidla sekcí Nadstavba nebudeme zabývat (nebo jen pokud zbyde čas). 

---

1) Úvod a motivace ([v prohlížeči](slides/intro.html), [ke stažení](https://ffuk-my.sharepoint.com/:b:/g/personal/mazaj7af_ff_cuni_cz/Ef--efsWGaJAvdJN2isxzZQBv6D_RgUUSdbBVB2unuv3nA?e=PyUSc8))
1) Kategorická data a procenta ([v prohlížeči](slides/categories.html), ke stažení)
1) Numerické proměnné a míry centrality ([v prohlížeči](slides/centrality.html), ke stažení)
1) Numerické proměnné a míry variability ([v prohlížeči](slides/variability.html), ke stažení)
1) Popis vztahů mezi proměnnými ([v prohlížeči](slides/relations.html), ke stažení)
1) Statistický model ([v prohlížeči](slides/model.html), ke stažení) 
1) Základy inferenčního uvažování: vzorek a populace ([v prohlížeči](slides/inference.html), ke stažení)
1) Pravděpodobnost, nejistota a variabilita ([v prohlížeči](slides/probability.html), ke stažení)
1) Centrální limitní věta ([v prohlížeči](slides/000clt.html), ke stažení)
1) Centrální limitní věta - opakování a rozšíření ([v prohlížeči](slides/000clt2.html), ke stažení)
1) Podmíněná pravděpodobnost a Bayesova věta ([v prohlížeči](slides/000conditional.html), ke stažení)
1) Bayesovská aktualizace na základě nových informací (v prohlížeči, ke stažení)


## Doplňkové prezentace a další ukázky

Protože občas se hodí mít pár slajdů v záloze...

* [Monty Hall](slides/99_MontyHall.html)
* [Bootstrapping](slides/000_99_bootstrapping.html)
