---
title: "unused"
author: "Jaromír Mazák"
date: "16 2 2022"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r libs}
library(tidyverse)
library(patchwork)
library(scales)
library(here)

# library(fGarch) # for desired skew. finally unused to reduce pck dependency
```


## Šikmost (Skewness)

```{r}


set.seed(42)

skew_neg <- ggplot(data=as_tibble(rbeta(1000,5,2)), aes(x = value)) + geom_histogram(color="white") + labs(title = "Záporná šikmost", x = "Rozsah proměnné je od 0 do 1", y = "Četnost") + annotate(geom="text", x=0.05, y=60, label="-", color="red", size = 20) + scale_x_continuous(limits = c(0,1))
skew_pos <- ggplot(data=as_tibble(rbeta(1000,2,5)), aes(x = value)) + geom_histogram(color="white") + labs(title = "Kladná šikmost", x = "Rozsah proměnné je od 0 do 1", y = "Četnost") + annotate(geom="text", x=0.95, y=60, label="+", color="red", size = 15) + scale_x_continuous(limits = c(0,1))
skew_0 <- ggplot(data=as_tibble(rbeta(1000,5,5)), aes(x = value)) + geom_histogram(color="white") + labs(title = "Nešikmé rozdělení", x = "Rozsah proměnné je od 0 do 1", y = "Četnost") + scale_x_continuous(limits = c(0,1))

skew_0 / skew_neg / skew_pos


# unused versions of illustrating skew

# left <- rnorm(1000, 10, 1) %>% log10() %>% hist()
# right <- rnorm(1000, 10, 1) %>% exp() %>% hist()
# rsnorm(1000, mean = 0, sd = 1, xi = 10) %>% hist()

```


::: {.notes}
Data mohou být buď symetrická (např. známé normální rozdělení čii Gausova křivka), nebo nesymetrická. Možným měřítkem nesymetričnosti je šikmost. 
:::